### ISSUE TITLE
Select/Copy result

### ISSUE THREAD

**Issue by Otard95** [jbyuki/quickmath.nvim#1]
Hey.

I realize this is likely your personal project, so i would create a PR to not impose to much.
But I'll admit I don't really have the experience necessary with nvim lua scripting.

My question/request is is there or can there be a feature to select/copy the virtual text(output)?

**Comment by jbyuki** [comment]
Hi,

That's a nice feature to add, I probably also needed it but could't copy directly the result.

I did a rough implementation. The idea is to be intuitive and the least intrusive.
You can see a video with the select/copy in action. 

https://user-images.githubusercontent.com/47322901/153907848-aaba32cd-7444-439f-a008-452e29304356.mp4

I wish I had key presses overlay. The presses I did were, once at the end of the line press '$',
this will jump the selection to the virtual text, yank in clipboard using 'y'.

Let me know if you think this is not too cumbersome/working.

**Comment by Otard95** [comment]
Wow that was fast. I didn't expect you to get back to me that fast, if at all, I appreciate that!

Yeah, I was messing around too, trying to figure out if there was a way to visually select virtual text, but I couldn't find a way.

If I understand you correctly, if I where to do `$` to get to the end of the line, and then `$` again I would then have the virtual text selected and could `y` it. If so i think that fits very very with the vim/nvim key bind theme. `$` is end, so `$$` is past the end, yeah I like it.

Unfortunately I'm unable to test it right now, but it'll be the first thing i do tomorrow morning.

**Comment by jbyuki** [comment]
That's the idea. It seemed to be the overall best way to implement selectable virtual text. I'm open to other possibilities.

Right, let me know how it works out.

**Comment by Otard95** [comment]
Got a chance to test now. I did get an error when loading the calc. I made a PR with a fix. I hope my limiter experience was enough to do so in a satisfactory way.

**Comment by Otard95** [comment]
PR merged, this one is all done and dusted 🚀
