### ISSUE TITLE
Underscores not allowed in variable names

### ISSUE THREAD

**Issue by hejops** [jbyuki/quickmath.nvim#7]
https://github.com/jbyuki/quickmath.nvim/blob/dcfc5450fa686714817a0d4767299f37f94bdb43/src/quickmath.lua.t#L57

As far as I can tell, lua's `%w` is unlike the "standard" [`\w`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet#character_classes) regex in that it does not include `_`. This means that variable names containing underscores are considered invalid (when they are valid in normal lua variable names, i.e. outside of quickmath).

**Comment by jbyuki** [comment]
That's a good point.
Could you PR it? I won't be on my laptop for a few days if you want it
corrected.

**Comment by hejops** [comment]
Sure, I'll get it done in a couple of days.

**Comment by jbyuki** [comment]
Thanks  🙏
